package com.restraunt.shapshuk.command;

import java.util.Optional;
import java.util.stream.Stream;

public enum CommandType {

    INDEX,
    SUBMIT_USER_LOGIN_COMMAND,
    LOGOUT,
    SUBMIT_USER_REGISTER_COMMAND,

    LOGIN_SERVLET_SWITCH,
    REGISTER_SERVLET_SWITCH,
    MENU_SERVLET_SWITCH,
    ORDER_BASKET_SERVLET_SWITCH,
    ORDER_CHECKOUT_SERVLET_SWITCH,

    DELETE_ORDER_ITEM_COMMAND,
    ADD_ORDER_ITEM_COMMAND,
    DISPLAY_ORDER_ITEM_LIST_COMMAND,
    DISPLAY_ORDER_CHECKOUT_COMMAND,
    SUBMIT_ORDER_CHECKOUT_COMMAND,

    DISPLAY_DISH_CREATING_FORM_COMMAND,
    SUBMIT_DISH_CREATING_FORM_COMMAND,
    DISPLAY_DISH_UPDATING_FORM_COMMAND,
    SUBMIT_DISH_UPDATING_FORM_COMMAND,
    DELETE_DISH_COMMAND,

    DISPLAY_DISH_CATEGORY_CREATING_FORM_COMMAND,
    SUBMIT_DISH_CATEGORY_CREATING_FORM_COMMAND,
    DISPLAY_DISH_CATEGORY_DELETING_FORM_COMMAND,
    SUBMIT_DISH_CATEGORY_DELETING_FORM_COMMAND,

    DISPLAY_FILLING_UP_WALLET_FORM_COMMAND,
    SUBMIT_FILLING_UP_WALLET_FORM_COMMAND,

    DISPLAY_DISH_FEEDBACK_CREATING_FORM_COMMAND,
    SUBMIT_DISH_FEEDBACK_CREATING_FORM_COMMAND,
    DISPLAY_DISH_MENU_COMMAND,

    DEFAULT;

    public static Optional<CommandType> of(String name) {
        return Stream.of(CommandType.values())
                .filter(type -> type.name().equalsIgnoreCase(name))
                .findFirst();
    }
}
